[workspace]
resolver = "3"
members = [
  # Shared protocol, storage, and support crates.
  "bula/src/*",
  "elegua/src/*",
  "jaku/src/*",
  "oya/src/*",
  "rustydb/src/*",

  # Ogun OS workspaces pulled in through git submodules.
  "ogun-apps/src/*",
  "ogun-components/src/apps/tier-2/*",
  "ogun-components/src/apps/tier-3/*",
  "ogun-components/src/drivers/*",
  "ogun-components/src/hosts/*",
  "ogun-components/src/services/*",
  "ogun-devices/src/*",
  "ogun-os/src/ogun-app",
  "ogun-os/src/ogun-host-server",
  # "ogun-os/src/ogun-mobile",
  "ogun-os/src/ogun-web",
  "ogun-os/src/ogun-desktop/src-tauri",
  "ogun-runtime/src/*",
  "ogun-sdk/src/*",
  # "ogun-tools/src/ogun-image-tool/src-tauri",
  "ogun-tools/src/ogun-setup/src-tauri",
  "ogun-test-features"
]

[workspace.package]
version = "0.1.0-alpha.3"
edition = "2024"
license = "GPL-3.0"
authors = ["Dominic Eaton", "Ogun Foundation"]
publish = false

[profile.dev]
opt-level = 0

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
